var $header = $('header');
var $h1 = $('h1');
var $main = $('main');
var $firstP = $('main p:first-child');
var $h2 = $('h2');
var $mainUl = $('main ul');
var $img = $('img');
var $slugListFirst = $('main ul li:first-child');
var $slugListLast = $('main ul li:last-child');
var $dl = $('dl');
var $dt = $('dt');

$header.addClass('masthead');
$h1.removeClass('big-heading');
$h1.addClass('logo');
$main.addClass('wrapper');
$firstP.addClass('intro');
$h2.addClass('slug-head');
$img.addClass('slug-img');
$slugListFirst.addClass('slug-list-first');
$slugListLast.addClass('slug-list-last');
$dl.addClass('classification');
$dt.removeClass('big-label');
$slugListLast.show();
